# Generated by Django 4.0.4 on 2022-05-03 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_userproductrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoppers',
            field=models.ManyToManyField(related_name='products', through='shop.UserProductRelation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
